services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: avocadodash:latest
    container_name: AvocadoDash
    command: "/bin/bash"
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace