sonar.projectKey=avocado-dash
sonar.projectName=AvocadoDash
sonar.projectVersion=1.0
sonar.language=py
sonar.python.version=3.14
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,src/assets/**,src/avocado.csv
sonar.coverage.exclusions=src/avocado.csv
sonar.python.coverage.reportPaths=tests/coverage.xml
